#!/bin/bash

unalias ll 2>/dev/null
alias ll='ls -l'
alias vi='vim'
alias rgc='rg -g "*.c" -g "*.cc" -g "*.cpp" -g "*.h" -g "*.hh" -g "*.hpp"'

export VISUAL=vim
export EDITOR="$VISUAL"

export HISTSIZE=1000
export HISTFILESIZE=2000

PATH=$PATH:~/.mjlenv/bin

SHELL_TYPE=$(basename $(echo $SHELL))
if [ $SHELL_TYPE = 'zsh' ]; then

    # Settings related to Cisco Meraki
    MERAKI=1
    if [ $MERAKI -eq 1 ]; then
        source ~/.mjlenv/meraki_init.sh
    fi

fi

if [ $SHELL_TYPE = 'bash' ]; then
    # Nvidia CUDA Stuff 
    export PATH=/usr/local/cuda-12.6/bin${PATH:+:${PATH}}
    export LD_LIBRARY_PATH=/usr/local/cuda-12.6/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
fi
