#!/bin/bash

unalias ll 2>/dev/null
alias ll='ls -l'
alias vi='vim'

export VISUAL=vim
export EDITOR="$VISUAL"

export HISTSIZE=1000
export HISTFILESIZE=2000

PATH=$PATH:~/.mjlenv/bin

SHELL_TYPE=$(basename $(echo $SHELL))
if [ $SHELL_TYPE = 'zsh' ]; then

    # Settings related to Cisco Meraki
    MERAKI=1
    if [ $MERAKI -eq 1 ]; then
        source meraki_init.sh
    fi

fi

